[package]
name = "HeurFuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
ndarray = "0.15"
fuzzywuzzy = "*"
